name: Build and push Docker image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: tarpisto

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Get commit SHA for Docker image tag
        id: sha
        run: echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USER }}
          password: ${{ secrets.PRIVATE_REGISTRY_PW }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for worker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.PRIVATE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=sha-${{ steps.sha.outputs.value }}

      - name: Build Docker image
        run: ./scripts/build-image.sh
        env:
          DOCKER_INFO: ${{ steps.meta.outputs.bake-file }}

      - name: Push Docker image
        run: docker push ${{ steps.meta.outputs.tags }}

      - name: Trigger deployment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          token: ${{ secrets.DEPLOYMENT_PAT }}
          workflow: Bump Service
          inputs: '{"service": "tarpisto", "tag": "sha-${{ steps.sha.outputs.value }}"}'
          repo: TKOaly/tko-aly-k8s-configs
          ref: main
