name: E2E Testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shards: [1, 2, 3, 4, 5]
        total_shards: [5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Run tests
        run: ./run-tests.sh
        env:
          PLAYWRIGHT_SHARD: ${{ matrix.shards }}
          PLAYWRIGHT_TOTAL_SHARDS: ${{ matrix.total_shards }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-results-${{ matrix.shards }}
          path: test-results
